# Generated by Django 5.2.4 on 2025-09-10 05:54

import django.db.models.deletion
import rekomtek.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Layanan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_layanan", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "1. Layanan",
            },
        ),
        migrations.CreateModel(
            name="PelaksanaanKontruksiDanPengalihanAir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nomor_surat",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "nama_pemohon",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tanggal_permohonan_sebelumnya",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "instansi_pemberi_permohonan_sebelumnya",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "kontak_pemohon",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "email_pemohon",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "lokasi_izin",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "koordinat_lintang",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "koordinat_bujur",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dok_surat_permohonan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/dokumen/",
                        validators=[rekomtek.models.validate_pdf],
                    ),
                ),
                (
                    "dok_profil_perusahaan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/dokumen/",
                        validators=[rekomtek.models.validate_pdf],
                    ),
                ),
                (
                    "dok_akte_notaris",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/dokumen/",
                        validators=[rekomtek.models.validate_pdf],
                    ),
                ),
                (
                    "dok_nib_oss",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/dokumen/",
                        validators=[rekomtek.models.validate_pdf],
                    ),
                ),
                (
                    "dok_ktp_direktur",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/dokumen/",
                        validators=[rekomtek.models.validate_pdf],
                    ),
                ),
                (
                    "dok_npwp_direktur",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/dokumen/",
                        validators=[rekomtek.models.validate_pdf],
                    ),
                ),
                (
                    "dok_npwp_kaltim",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/dokumen/",
                        validators=[rekomtek.models.validate_pdf],
                    ),
                ),
                (
                    "dok_peta_lokasi",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/dokumen/",
                        validators=[rekomtek.models.validate_pdf],
                    ),
                ),
                (
                    "dok_desain_bangunan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/dokumen/",
                        validators=[rekomtek.models.validate_pdf],
                    ),
                ),
                (
                    "dok_spesifikasi_teknis",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/dokumen/",
                        validators=[rekomtek.models.validate_pdf],
                    ),
                ),
                (
                    "dok_analisa_perhitungan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/dokumen/",
                        validators=[rekomtek.models.validate_pdf],
                    ),
                ),
                (
                    "dok_jadwal_pelaksanaan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/dokumen/",
                        validators=[rekomtek.models.validate_pdf],
                    ),
                ),
                (
                    "dok_manual_operasi",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/dokumen/",
                        validators=[rekomtek.models.validate_pdf],
                    ),
                ),
                (
                    "dok_sertifikat_tanah",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/dokumen/",
                        validators=[rekomtek.models.validate_pdf],
                    ),
                ),
                (
                    "dok_lingkungan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/dokumen/",
                        validators=[rekomtek.models.validate_pdf],
                    ),
                ),
                (
                    "dok_berita_acara",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/dokumen/",
                        validators=[rekomtek.models.validate_pdf],
                    ),
                ),
                (
                    "dok_surat_kuasa",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/dokumen/",
                        validators=[rekomtek.models.validate_pdf],
                    ),
                ),
                ("pertimbangan", models.TextField(blank=True, null=True)),
                ("saran_masukan", models.TextField(blank=True, null=True)),
                (
                    "nomor_pertimbangan",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tanggal_pertimbangan", models.DateField(blank=True, null=True)),
                (
                    "dok_pertimbangan",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/dokumen/",
                        validators=[rekomtek.models.validate_pdf],
                    ),
                ),
                ("catatan", models.TextField(blank=True, null=True)),
                ("tanggal_permohonan", models.DateField(auto_now_add=True)),
                (
                    "layanan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rekomtek.layanan",
                    ),
                ),
                (
                    "permohonan_lama",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="perpanjangan",
                        to="rekomtek.pelaksanaankontruksidanpengalihanair",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "5. Rekomendasi Konstruksi & Pengalihan Air",
            },
        ),
        migrations.CreateModel(
            name="RekomendasiTeknis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nomor_surat",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "nama_pemohon",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "kontak_pemohon",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "email_pemohon",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "nama_perusahaan",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nama_direktur",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "alamat_perusahaan",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                ("tanggal_permohonan", models.DateField(auto_now_add=True)),
                (
                    "tanggal_permohonan_sebelumnya",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "instansi_pemberi_permohonan_sebelumnya",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dok_gambar_desain",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/dokumen/"
                    ),
                ),
                (
                    "dok_izin_lingkungan",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/dokumen/"
                    ),
                ),
                (
                    "dok_berita_acara",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/dokumen/"
                    ),
                ),
                (
                    "dok_jenis_prasarana",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/dokumen/"
                    ),
                ),
                (
                    "dok_kepemilikan_lahan",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/dokumen/"
                    ),
                ),
                (
                    "dok_perizinan_usaha",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/dokumen/"
                    ),
                ),
                (
                    "dok_proposal_teknis",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/dokumen/"
                    ),
                ),
                (
                    "dok_rencana_operasi",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/dokumen/"
                    ),
                ),
                (
                    "dok_surat_permohonan",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/dokumen/"
                    ),
                ),
                (
                    "jenis_permohonan",
                    models.CharField(
                        choices=[
                            ("baru", "Permohonan Baru"),
                            ("perpanjangan", "Perpanjangan"),
                        ],
                        default="baru",
                        max_length=20,
                    ),
                ),
                (
                    "layanan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rekomtek.layanan",
                    ),
                ),
                (
                    "permohonan_lama",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="perpanjangan",
                        to="rekomtek.rekomendasiteknis",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "2. Rekomendasi Teknis",
            },
        ),
        migrations.CreateModel(
            name="Intake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sumber_air",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sungai", "Sungai"),
                            ("danau", "Danau"),
                            ("waduk_/_kolam_tampungan", "Waduk / Kolam Tampungan"),
                            ("mata_air", "Mata Air"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "kelurahan_desa",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("kecamatan", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "kabupaten_kota",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("provinsi", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "titik_koordinat",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tujuan_pemanfaatan", models.TextField(blank=True, null=True)),
                ("cara_pengambilan_air", models.TextField(blank=True, null=True)),
                ("cara_pembuangan_air", models.TextField(blank=True, null=True)),
                (
                    "volume_pengambilan",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "lama_waktu_pengambilan",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "jenis_pompa",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "kapasitas_pompa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "upload_name_plate_pompa",
                    models.FileField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "rekomtek",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intakes",
                        to="rekomtek.rekomendasiteknis",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "4. Data Intake",
            },
        ),
        migrations.CreateModel(
            name="StatusRekomendasiTeknis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proses", "Sedang Diproses"),
                            ("diterima", "Diterima"),
                            ("ditolak", "Ditolak"),
                        ],
                        default="proses",
                        max_length=20,
                    ),
                ),
                ("keterangan", models.TextField(blank=True, null=True)),
                (
                    "tanggal_realisasi_kunjungan_lapangan",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "jadwal_monitoring",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                ("tanggal_kirim", models.DateField(auto_now=True)),
                (
                    "rekomtek",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_rekomtek",
                        to="rekomtek.rekomendasiteknis",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "3. Status Rekomendasi Teknis",
            },
        ),
    ]
