# Generated by Django 5.2.4 on 2025-09-10 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rekomtek", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statusrekomendasiteknis",
            name="pelaksanaan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_pelaksanaan",
                to="rekomtek.rekomendasiteknis",
            ),
        ),
    ]
