# Generated by Django 5.2.4 on 2025-08-12 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rekomtek", "0002_alter_layanan_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="deskripsi",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="foto_lokasi",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="jumlah_usulan",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="koordinat_latitude",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="koordinat_longitude",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="lokasi",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="nama_usulan",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="tujuan",
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="alamat_perusahaan",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="berita_acara",
            field=models.FileField(blank=True, null=True, upload_to="dokumen/"),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="cara_pembuangan_air",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="cara_pengambilan_air",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="dokumen_lahan",
            field=models.FileField(blank=True, null=True, upload_to="dokumen/"),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="dokumentasi_prasarana",
            field=models.FileField(blank=True, null=True, upload_to="dokumen/"),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="gambar_detail",
            field=models.FileField(blank=True, null=True, upload_to="dokumen/"),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="izin_lingkungan",
            field=models.FileField(blank=True, null=True, upload_to="dokumen/"),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="jenis_pompa",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="kabupaten_kota",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="kapasitas_pompa",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Liter/detik",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="kecamatan",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="kelurahan",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="lama_pengambilan",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Jam/hari",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="lokasi_pengambilan",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="nama_direktur",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="nama_perusahaan",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="name_plate_pompa",
            field=models.FileField(blank=True, null=True, upload_to="dokumen/"),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="pengambilan_sumber_air",
            field=models.CharField(
                blank=True,
                help_text="Contoh: Intake Sungai X",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="perizinan_berusaha",
            field=models.FileField(blank=True, null=True, upload_to="dokumen/"),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="proposal_teknis",
            field=models.FileField(blank=True, null=True, upload_to="dokumen/"),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="provinsi",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="rencana_operasi",
            field=models.FileField(blank=True, null=True, upload_to="dokumen/"),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="sumber_air",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="surat_permohonan",
            field=models.FileField(blank=True, null=True, upload_to="dokumen/"),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="titik_koordinat",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="tujuan_pemanfaatan",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="volume_pengambilan",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Liter/detik",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rekomendasiteknis",
            name="email_pemohon",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="rekomendasiteknis",
            name="kontak_pemohon",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="rekomendasiteknis",
            name="layanan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rekomtek.layanan",
            ),
        ),
        migrations.AlterField(
            model_name="rekomendasiteknis",
            name="nama_pemohon",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
