# Generated by Django 5.2.4 on 2025-09-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rekomtek", "0003_alter_statusrekomendasiteknis_pelaksanaan"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pelaksanaankontruksidanpengalihanair",
            options={
                "verbose_name_plural": "5. Pelaksanaan Konstruksi dan Pengalihan Air"
            },
        ),
        migrations.RenameField(
            model_name="pelaksanaankontruksidanpengalihanair",
            old_name="lokasi_izin",
            new_name="alamat_perusahaan",
        ),
        migrations.RemoveField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="koordinat_bujur",
        ),
        migrations.RemoveField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="koordinat_lintang",
        ),
        migrations.AddField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="jenis_permohonan",
            field=models.CharField(
                choices=[("baru", "Permohonan Baru"), ("perpanjangan", "Perpanjangan")],
                default="baru",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="nama_direktur",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="nama_perusahaan",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="dok_akte_notaris",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AlterField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="dok_analisa_perhitungan",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AlterField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="dok_berita_acara",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AlterField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="dok_desain_bangunan",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AlterField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="dok_jadwal_pelaksanaan",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AlterField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="dok_ktp_direktur",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AlterField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="dok_lingkungan",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AlterField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="dok_manual_operasi",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AlterField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="dok_nib_oss",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AlterField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="dok_npwp_direktur",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AlterField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="dok_npwp_kaltim",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AlterField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="dok_pertimbangan",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AlterField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="dok_peta_lokasi",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AlterField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="dok_profil_perusahaan",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AlterField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="dok_sertifikat_tanah",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AlterField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="dok_spesifikasi_teknis",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AlterField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="dok_surat_kuasa",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AlterField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="dok_surat_permohonan",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AlterField(
            model_name="pelaksanaankontruksidanpengalihanair",
            name="nomor_pertimbangan",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
