# Generated by Django 5.2.4 on 2025-08-12 06:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "rekomtek",
            "0004_rename_alamat_perusahaan_rekomendasiteknis_deskripsi_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="rekomendasiteknis",
            old_name="jumlah_usulan",
            new_name="alamat_perusahaan",
        ),
        migrations.RenameField(
            model_name="rekomendasiteknis",
            old_name="lokasi",
            new_name="nama_direktur",
        ),
        migrations.RenameField(
            model_name="rekomendasiteknis",
            old_name="nama_usulan",
            new_name="nama_perusahaan",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="deskripsi",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="foto_lokasi",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="koordinat_latitude",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="koordinat_longitude",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="tujuan",
        ),
    ]
