# Generated by Django 5.2.4 on 2025-08-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "rekomtek",
            "0005_rename_jumlah_usulan_rekomendasiteknis_alamat_perusahaan_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="cara_pembuangan_air",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="cara_pengambilan_air",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="jenis_pompa",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="kabupaten_kota",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="kapasitas_pompa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="kecamatan",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="kelurahan_desa",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="lama_waktu_pengambilan",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="provinsi",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="sumber_air",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sungai", "Sungai"),
                    ("danau", "Danau"),
                    ("sumur", "Sumur"),
                    ("mata_air", "Mata Air"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="titik_koordinat",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="tujuan_pemanfaatan",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="upload_name_plate_pompa",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="volume_pengambilan",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="rekomendasiteknis",
            name="alamat_perusahaan",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
