# Generated by Django 5.2.4 on 2025-08-12 07:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rekomtek", "0006_rekomendasiteknis_cara_pembuangan_air_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="cara_pembuangan_air",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="cara_pengambilan_air",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="jenis_pompa",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="kabupaten_kota",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="kapasitas_pompa",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="kecamatan",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="kelurahan_desa",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="lama_waktu_pengambilan",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="provinsi",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="sumber_air",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="titik_koordinat",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="tujuan_pemanfaatan",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="upload_name_plate_pompa",
        ),
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="volume_pengambilan",
        ),
    ]
