# Generated by Django 5.2.4 on 2025-08-12 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rekomtek", "0007_remove_rekomendasiteknis_cara_pembuangan_air_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sumber_air",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sungai", "Sungai"),
                            ("danau", "Danau"),
                            ("sumur", "Sumur"),
                            ("mata_air", "Mata Air"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "kelurahan_desa",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("kecamatan", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "kabupaten_kota",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("provinsi", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "titik_koordinat",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tujuan_pemanfaatan", models.TextField(blank=True, null=True)),
                ("cara_pengambilan_air", models.TextField(blank=True, null=True)),
                ("cara_pembuangan_air", models.TextField(blank=True, null=True)),
                (
                    "volume_pengambilan",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "lama_waktu_pengambilan",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "jenis_pompa",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "kapasitas_pompa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "upload_name_plate_pompa",
                    models.FileField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "rekomtek",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intakes",
                        to="rekomtek.rekomendasiteknis",
                    ),
                ),
            ],
        ),
    ]
