# Generated by Django 5.2.4 on 2025-08-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rekomtek", "0008_intake"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="intake",
            options={"verbose_name_plural": "4. Data Intake"},
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="dok_berita_acara",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="dok_gambar_desain",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="dok_izin_lingkungan",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="dok_jenis_prasarana",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="dok_kepemilikan_lahan",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="dok_perizinan_usaha",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="dok_proposal_teknis",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="dok_rencana_operasi",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="dok_surat_permohonan",
            field=models.FileField(blank=True, null=True, upload_to="uploads/dokumen/"),
        ),
    ]
