# Generated by Django 5.2.4 on 2025-08-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rekomtek", "0009_alter_intake_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intake",
            name="sumber_air",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sungai", "Sungai"),
                    ("danau", "Danau"),
                    ("waduk_/_kolam_tampungan", "Waduk / Kolam Tampungan"),
                    ("mata_air", "Mata Air"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
