# Generated by Django 5.2.4 on 2025-08-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rekomtek", "0010_alter_intake_sumber_air"),
    ]

    operations = [
        migrations.AddField(
            model_name="statusrekomendasiteknis",
            name="keterangan",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="statusrekomendasiteknis",
            name="status",
            field=models.CharField(
                choices=[("diterima", "Diterima"), ("ditolak", "Ditolak")],
                default="diterima",
                max_length=20,
            ),
        ),
    ]
