# Generated by Django 5.2.4 on 2025-08-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rekomtek", "0011_statusrekomendasiteknis_keterangan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statusrekomendasiteknis",
            name="status",
            field=models.CharField(
                choices=[
                    ("proses", "Sedang Diproses"),
                    ("diterima", "Diterima"),
                    ("ditolak", "Ditolak"),
                ],
                default="proses",
                max_length=20,
            ),
        ),
    ]
