# Generated by Django 5.2.4 on 2025-08-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rekomtek", "0012_alter_statusrekomendasiteknis_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="statusrekomendasiteknis",
            name="tanggal_kirim",
            field=models.DateField(auto_now=True),
        ),
    ]
