# Generated by Django 5.2.4 on 2025-08-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rekomtek", "0015_rekomendasiteknis_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="rekomendasiteknis",
            name="tanggal_kirim",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
