# Generated by Django 5.2.4 on 2025-08-28 05:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rekomtek", "0016_rekomendasiteknis_tanggal_kirim"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rekomendasiteknis",
            name="tanggal_kirim",
        ),
    ]
