# Generated by Django 5.2.4 on 2025-08-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rekomtek", "0017_remove_rekomendasiteknis_tanggal_kirim"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statusrekomendasiteknis",
            name="jadwal_kunjungan_lapangan",
        ),
        migrations.RemoveField(
            model_name="statusrekomendasiteknis",
            name="tanggal_kunjungan_lapangan_2",
        ),
        migrations.AddField(
            model_name="statusrekomendasiteknis",
            name="jadwal_monitoring",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
