"""
Django settings for websda project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-s7eijtn0f9dixh&m=1qui^)xyq7)bz$mi174fv&29jzvb4d03g"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "berita",
    "pengguna",
    "rekomtek",
    "profil",
    "kelembagaan",
    "layanan_publik",
    'ckeditor',
    "infrastruktur_sda",
    "galeri",
    "perencanaan_kinerja",
    "media_informasi",
    "hasil_survey_kepuasan",
    "informasi_sda",
    "contact",  
    'widget_tweaks', 
    "dashboard",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "websda.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR, 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "dashboard.profil_context.profil_context",
            ],
        },
    },
]

WSGI_APPLICATION = "websda.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
       'ENGINE': 'django.db.backends.mysql', 
        'NAME': 'sda_database',
        'USER': 'root',
        'PASSWORD': 'Samarinda123_',
        'HOST': '127.0.0.1',   # Or an IP Address that your DB is hosted on
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = 'Asia/Makassar'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Boleh di-iframe dari domain sendiri
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



# ckeditor config 
CKEDITOR_UPLOAD_PATH = "upload/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'height': 300,
        'width': 'auto',
        'toolbar_Custom': [
            ['Styles', 'Format', 'Bold', 'Italic', 'Underline', 'Strike', 'SpellChecker', 'Undo', 'Redo'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Flash', 'Table', 'HorizontalRule'],
            ['TextColor', 'BGColor'],
            ['Smiley', 'SpecialChar'], ['Source'],
        ],
    },
    'special': {
        'toolbar': 'Special',
        'width': 'auto',
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            {'name': 'forms',
             'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton',
                       'HiddenField']},
            '/',
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
                       'Language']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert',
             'items': ['Image', 'Youtube','Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']},
            '/',
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
            {'name': 'about', 'items': ['About']},
            '/',  # put this to force next toolbar on new line
            {'name': 'yourcustomtools', 'items': [
                # put the name of your editor.ui.addButton here
                'Preview',
                'Maximize',

            ]},
        ],
        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage', # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            # 'devtools',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath',
            'codesnippet', 
            'youtube'
        ]),
    }
}
# end ckeditor config 

JAZZMIN_SETTINGS = {
    "site_title": "PU Admin",
    "site_header": "DASHBOARD ADMIN",
    "welcome_sign": "Selamat datang di Admin PU",        # Logo di sidebar/header
    "site_icon": "halaman/assets/img/logopemprov.png",         # Favicon di tab browser
    "site_brand": "DASHBOARD ADMIN",                                   # Nama brand di header
    "site_logo_classes": "img-circle elevation-3",              # Styling opsional
    "show_sidebar": True,
    "navigation_expanded": False,
    "custom_css": "css/custom_admin.css",

    # Urutan aplikasi di sidebar
    "order_with_respect_to": [
        "galeri",
        "berita",
        "profil",
        "layanan_publik",
        "kelembagaan",
        "media_informasi",
        "auth",
    ],

    # Ikon untuk model agar lebih visual
    "icons": {
        # Galeri
        "galeri.KategoriKegiatanFisik": "fas fa-list-alt",
        "galeri.KategoriKegiatanPerencanaan": "fas fa-tasks",
        "galeri.KegiatanFisik": "fas fa-hard-hat",
        "galeri.FotoKegiatanFisik": "fas fa-camera",
        "galeri.VideoKegiatanFisik": "fas fa-video",
        "galeri.KegiatanPerencanaan": "fas fa-project-diagram",
        "galeri.FotoKegiatanPerencanaan": "fas fa-camera-retro",
        "galeri.VideoKegiatanPerencanaan": "fas fa-film",

        # Berita
        "berita.Kategori": "fas fa-folder-open",
        "berita.Artikel": "fas fa-newspaper",

        # Profil
        "profil.VisiMisi": "fas fa-bullseye",
        "profil.TugasFungsi": "fas fa-clipboard-list",
        "profil.StrukturOrganisasi": "fas fa-sitemap",

        # Kelembagaan
        "kelembagaan.TPS3R": "fas fa-recycle",

        # Layanan Publik
        "layanan_publik.Persampahan": "fas fa-trash-alt",
        "layanan_publik.SPALD": "fas fa-water",

        # Media Informasi
        "media_informasi.MajalahBanyu": "fas fa-book-open",

        # Auth
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",
    },

    # Link khusus di sidebar

}