# Generated by Django 5.2.4 on 2025-08-25 03:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_alter_pesankontak_tanggal_kirim"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PesanKontak",
        ),
    ]
