# Generated by Django 5.2.4 on 2025-08-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MajalahBanyu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=200)),
                ("file_majalah", models.FileField(upload_to="majalah_banyu/")),
                ("tanggal_upload", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Majalah Banyu",
            },
        ),
    ]
