# Generated by Django 5.2.4 on 2025-08-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Peraturan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(blank=True, max_length=255, null=True)),
                ("file", models.FileField(upload_to="file_peraturan/")),
                ("tanggal_upload", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "1. Peraturan",
            },
        ),
        migrations.CreateModel(
            name="SOP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(blank=True, max_length=255, null=True)),
                ("file", models.FileField(upload_to="file_sop/")),
                ("tanggal_upload", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "2. SOP",
            },
        ),
    ]
