# Generated by Django 5.2.4 on 2025-08-26 23:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("galeri", "0013_videokegiatanperencanaan_alter_video_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="foto",
            options={"verbose_name_plural": "3. Foto Fisik"},
        ),
        migrations.AlterModelOptions(
            name="fotokegiatanperencanaan",
            options={"verbose_name_plural": "4.Foto Perencanaan"},
        ),
        migrations.AlterModelOptions(
            name="kategorikegiatanfisik",
            options={"verbose_name_plural": "1. Kategori Fisik"},
        ),
        migrations.AlterModelOptions(
            name="kategorikegiatanperencanaan",
            options={"verbose_name_plural": "2. Kategori Perencanaan"},
        ),
        migrations.AlterModelOptions(
            name="video",
            options={"verbose_name_plural": "5. Video Fisik"},
        ),
        migrations.AlterModelOptions(
            name="videokegiatanperencanaan",
            options={"verbose_name_plural": "6. Video Perencanaan"},
        ),
    ]
