# Generated by Django 5.2.4 on 2025-08-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ikm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(blank=True, max_length=255, null=True)),
                ("file", models.FileField(upload_to="Indeks_Kepuasan_masyarakat/")),
                ("tanggal_upload", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "1. Indeks Kepuasan Masyarakat",
            },
        ),
    ]
