# Generated by Django 5.2.4 on 2025-08-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hasil_survey_kepuasan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hidrologi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="Hidrologi/"),
                ),
                ("tanggal_upload", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "2. Hidrologi",
            },
        ),
        migrations.AlterField(
            model_name="ikm",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="Indeks_Kepuasan_masyarakat/"
            ),
        ),
    ]
