# Generated by Django 5.2.4 on 2025-08-26 23:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hasil_survey_kepuasan", "0002_hidrologi_alter_ikm_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ikm",
            options={"verbose_name_plural": "1. IKM"},
        ),
    ]
