# Generated by Django 5.2.4 on 2025-08-25 03:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pengguna", "0002_alter_biodata_foto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Biodata",
        ),
    ]
